export const dummyProducts = [
  {
    id: 1,
    name: "Mineral Water",
    category: "Drinks",
    price: 5000,
    description: "Fresh and pure mountain spring water.",
    image:
      "https://via.placeholder.com/150?text=Orange+Juice",
  },
  {
    id: 2,
    name: "Iced Coffee",
    category: "Drinks",
    price: 15000,
    description: "A strong brew of iced coffee to start your day.",
    image:
      "https://via.placeholder.com/150?text=Orange+Juice",
  },
  {
    id: 3,
    name: "Potato Chips",
    category: "Snacks",
    price: 8000,
    description: "Crispy and savory potato chips.",
    image:
      "https://via.placeholder.com/150?text=Orange+Juice",
  },
  {
    id: 4,
    name: "Chocolate Bar",
    category: "Snacks",
    price: 12000,
    description: "Rich and decadent chocolate bar.",
    image: "https://via.placeholder.com/150?text=Chocolate+Bar",
  },
  {
    id: 5,
    name: "Snack Bundle",
    category: "Bundles",
    price: 25000,
    description: "A complete bundle of joy for your movie night.",
    image: "https://via.placeholder.com/150?text=Snack+Bundle",
  },
  // --- Produk Baru Ditambahkan Di Sini ---
  {
    id: 6,
    name: "Orange Juice",
    category: "Drinks",
    price: 12000,
    description: "Freshly squeezed orange juice, full of vitamins.",
    image: "https://via.placeholder.com/150?text=Orange+Juice",
  },
  {
    id: 7,
    name: "Green Tea",
    category: "Drinks",
    price: 10000,
    description: "A calming and refreshing cup of green tea.",
    image: "https://via.placeholder.com/150?text=Green+Tea",
  },
  {
    id: 8,
    name: "Cashew Nuts",
    category: "Snacks",
    price: 18000,
    description: "Roasted and lightly salted cashew nuts.",
    image: "https://via.placeholder.com/150?text=Cashew+Nuts",
  },
  {
    id: 9,
    name: "Popcorn",
    category: "Snacks",
    price: 9000,
    description: "Classic buttered popcorn for any occasion.",
    image: "https://via.placeholder.com/150?text=Popcorn",
  },
  {
    id: 10,
    name: "Healthy Bundle",
    category: "Bundles",
    price: 35000,
    description: "A mix of nuts, dried fruits, and green tea.",
    image: "https://via.placeholder.com/150?text=Healthy+Bundle",
  },
  {
    id: 11,
    name: "Breakfast Bundle",
    category: "Bundles",
    price: 40000,
    description: "Iced coffee and a croissant to kickstart your morning.",
    image: "https://via.placeholder.com/150?text=Breakfast+Bundle",
  },
];
